New kernel config trying to get the modules to build.
Currently breaking due to missing CONFIG_AVERAGE in base kernel.

MODPOST 6 modules
ERROR: "ewma_init" [net/mac80211/mac80211.ko] undefined!
ERROR: "ewma_add" [net/mac80211/mac80211.ko] undefined!
make[1]: *** [__modpost] Error 1